[package]
name = "ckb-pcn-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.2", features = ["derive", "env"] }
clap-serde-derive = "0.2.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
lightning = { version = "0.0.121", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.121", features = [
    "rpc-client",
    "tokio",
] }
lightning-invoice = { version = "0.29.0" }
lightning-net-tokio = { version = "0.0.121" }
lightning-persister = { version = "0.0.121" }
lightning-background-processor = { version = "0.0.121", features = ["futures"] }
lightning-rapid-gossip-sync = { version = "0.0.121" }

base64 = "0.22.0"
bitcoin = { version = "0.31.1", features = ["serde"] }
bitcoin-bech32 = "0.13"
bech32 = "0.11"
libc = "0.2.142"

chrono = { version = "0.4", default-features = false, features = ["clock"] }
rand = "0.8.5"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "net",
    "time",
] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
